fix: Added separate timestamps for deposit and execution
sygmaprotocol/sygma-explorer-indexer pull request #119
Opened 2023-10-06 12:02 UTC by mj52951

Timestamp of deposit and timestamp of execution are now two separate entries in the database. By updating the database, I've refactored the code and tests to function properly. 

closes: #112

2023-10-10 11:03 UTC, tcar121293 requested changes

2023-10-10 11:03 UTC, tcar121293 commented on src/services/transfers.service.ts
> -          timestamp: "desc",
We should order it by deposit.timestamp

2023-10-11 10:49 UTC, mpetrun5 approved these changes
LGTM
Just fix Tihomir's comment

2023-10-18 14:24 UTC, wainola approved these changes

2023-10-26 08:18 UTC, tcar121293 approved these changes

2023-10-26 08:19 UTC, merged