feat: update transfers/txHash/:txHash endpoint
sygmaprotocol/sygma-explorer-indexer pull request #169
Opened 2024-02-08 08:54 UTC by tcar121293

update transfers/txHash/:txHash endpoint
## Description
return array of transfers instead of object

## Related Issue Or Context

Closes: #154

## How Has This Been Tested? Testing details.
e2e tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in chainbridge-docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-02-08 10:45 UTC, MakMuftic commented
@wainola we need to prepare UI for this change

2024-02-08 13:48 UTC, tcar121293 commented
> @wainola we need to prepare UI for this change

I think this endpoint is currently not used by the explorer-ui. But let @wainola confirm that

2024-02-09 14:47 UTC, wainola commented
> > @wainola we need to prepare UI for this change
> 
> I think this endpoint is currently not used by the explorer-ui. But let @wainola confirm that

we use `/transfer/:transferId` on the detail view. But the url has the txHash. Are we going to change this and use this endpoint @MakMuftic?

2024-02-09 15:10 UTC, MakMuftic commented
@wainola I think we should change and use this endpoint instead. I'm not sure if something is missing for this change to be implemented on the UI, @wainola let us know if you think we need to add something else :) 

@tcar121293 then we can merge this as it will not brake anything

2024-02-09 15:19 UTC, wainola requested changes

2024-02-09 15:19 UTC, wainola commented on src/services/transfers.service.ts
> +  public async findTransferByTxHash(txHash: string, domainID: number): Promise<Transfer[]> {
would it be more semantic `findTransfersByTxHash`?

2024-02-09 15:57 UTC, wainola approved these changes

2024-02-09 16:05 UTC, wainola commented
> @wainola I think we should change and use this endpoint instead. I'm not sure if something is missing for this change to be implemented on the UI, @wainola let us know if you think we need to add something else :)
> 
> @tcar121293 then we can merge this as it will not brake anything

I can add this to the current explorer UI issue related to the query param

2024-02-12 13:18 UTC, merged