chore: test latest indexing logic
sygmaprotocol/sygma-explorer-indexer pull request #91
Opened 2023-07-26 12:47 UTC by mj52951

## Description
Added e2e testing file and github action for testing 

## Related Issue Or Context
Part of issue #47

2023-07-26 12:56 UTC, wainola requested changes

2023-07-26 12:56 UTC, wainola commented on .gitignore
> +/dist-cjs
why do we need to add this?

2023-07-26 12:56 UTC, wainola commented on .gitignore
> +tsconfig.cjs.json
same question as above for both of that files

2023-07-26 13:16 UTC, mpetrun5 requested changes

2023-07-27 08:30 UTC, mpetrun5 approved these changes

2023-07-27 12:15 UTC, wainola requested changes

2023-07-27 12:15 UTC, wainola commented on tests/e2e/indexing.spec.ts
> +        /* --- There are currently no evm2 => Ethereum 1 transfers ---
Should we remove this commented code?

Same question for below commented code

@mpetrun5

2023-07-27 12:15 UTC, wainola approved these changes

2023-07-27 12:35 UTC, merged